
# What is PyTorch?

It’s a Python based scientific computing package targeted at two sets of audiences:

-  Tensorial library that uses the power of GPUs
-  A deep learning research platform that provides maximum flexibility and speed

## Import the library

In [1]:
import torch  # <Ctrl> / <Shift> + <Return>

## Getting help in Jupyter

In [2]:
torch.sqrt # <Tab>

<function _VariableFunctionsClass.sqrt>

In [6]:
# What about all `*Tensor`s?
# Press <esc> to get out of help
torch.*Tensor?

In [4]:
torch.nn.Module()  # <Shift>+<Tab>

Module()

In [5]:
# Annotate your functions / classes!
torch.nn.Module?

In [ ]:
torch.nn.Module??

## Dropping to Bash: magic!

In [ ]:
# List all the files in the current directory
!ls -lh

In [ ]:
%%bash
# List all the files but with cleaner outputs for readability
for f in $(ls *.*); do
    echo $(wc -l $f)
done

In [ ]:
# Getting some general help
%magic

## Python native data types

Python has many native datatypes. Here are the important ones:

 - **Booleans** are either `True` or `False`.
 - **Numbers** can be integers (1 and 2), floats (1.1 and 1.2), fractions (1/2 and 2/3), or even complex numbers.
 - **Strings** are sequences of Unicode characters, e.g. an html document.
 - **Lists** are ordered sequences of values.
 - **Tuples** are ordered, immutable sequences of values.
 - **Sets** are unordered bags of values.
 - **Dictionaries** are unordered bags of key-value pairs.
 
See [here](http://www.diveintopython3.net/native-datatypes.html) for a complete overview.

### More resources

 1. Brief Python introduction [here](https://learnxinyminutes.com/docs/python3/).
 2. Full Python tutorial [here](https://docs.python.org/3/tutorial/).
 3. A Whirlwind Tour of Python [here](https://github.com/jakevdp/WhirlwindTourOfPython).
 4. Python Data Science Handbook [here](https://github.com/jakevdp/PythonDataScienceHandbook).

## Torch!

In [ ]:
# Generate a tensor of size 2x3x4
t = torch.Tensor(2, 3, 4)
type(t)

In [ ]:
# Get the size of the tensor
t.size()

In [ ]:
# t.size() is a classic tuple =>
print('t size:', ' \u00D7 '.join(map(str, t.size())))

In [ ]:
# prints dimensional space and sub-dimensions
print(f'point in a {t.numel()} dimensional space')
print(f'organised in {t.dim()} sub-dimensions')

In [ ]:
t

In [ ]:
# Mind the underscore!
# Any operation that mutates a tensor in-place is post-fixed with an _.
# For example: x.copy_(y), x.t_(), x.random_(n) will change x.
t.random_(10)

In [ ]:
t

In [ ]:
# This resizes the tensor permanently 
r = torch.Tensor(t)
r.resize_(3, 8)
r

In [ ]:
# As you can see zero_ would replace r with 0's which was originally filled with integers
r.zero_()

In [ ]:
t

In [ ]:
# This *is* important, sigh...
s = r.clone()

In [ ]:
# In-place fill of 1's
s.fill_(1)
s

In [ ]:
# Because we cloned r, even though we did an in-place operation, this doesn't affect r
r

## Vectors (1D Tensors)

In [ ]:
# Creates a 1D tensor of integers 1 to 4
v = torch.Tensor([1, 2, 3, 4])
v

In [ ]:
# Print number of dimensions (1D) and size of tensor
print(f'dim: {v.dim()}, size: {v.size()[0]}')

In [ ]:
w = torch.Tensor([1, 0, 2, 0])
w

In [ ]:
# Element-wise multiplication
v * w

In [ ]:
# Scalar product: 1*1 + 2*0 + 3*2 + 4*0
v @ w

In [ ]:
# In-place replacement of random number from 0 to 10
x = torch.Tensor(5).random_(10)
x

In [ ]:
print(f'first: {x[0]}, last: {x[-1]}')

In [ ]:
# Extract sub-Tensor [from:to)
x[1:2 + 1]

In [ ]:
v

In [ ]:
# Create a tensor with integers ranging from 1 to 5, excluding 5
v = torch.arange(1, 4 + 1)
v

In [ ]:
# Square all elements in the tensor
print(v.pow(2), v)

## Matrices (2D Tensors)

In [7]:
# Create a 2x4 tensor
m = torch.Tensor([[2, 5, 3, 7],
                  [4, 2, 1, 9]])
m

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [8]:
m.dim()

2

In [9]:
print(m.size(0), m.size(1), m.size(), sep=' -- ')

2 -- 4 -- torch.Size([2, 4])


In [10]:
# Returns the total number of elements, hence num-el (number of elements)
m.numel()

8

In [11]:
# Indexing row 0, column 2 (0-indexed)
m[0][2]

tensor(3.)

In [12]:
# Indexing row 0, column 2 (0-indexed)
m[0, 2]

tensor(3.)

In [13]:
# Indexing column 1, all rows (returns size 2)
m[:, 1]

tensor([5., 2.])

In [14]:
# Indexing column 1, all rows (returns size 2x2)
m[:, [1]]

tensor([[5.],
        [2.]])

In [15]:
# Indexes row 0, all columns (returns 1x4)
m[[0], :]

tensor([[2., 5., 3., 7.]])

In [16]:
# Indexes row 0, all columns (returns size 4)
m[0, :]

tensor([2., 5., 3., 7.])

In [17]:
# Create tensor of numbers from 1 to 5 (excluding 5)
v = torch.arange(1., 4 + 1)
v

tensor([1., 2., 3., 4.])

In [18]:
m

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [19]:
# Scalar product
m @ v

tensor([49., 47.])

In [20]:
# Calculated by 1*2 + 2*5 + 3*3 + 4*7
m[[0], :] @ v

tensor([49.])

In [21]:
# Calculated by 
m[[1], :] @ v

tensor([47.])

In [22]:
# Add a random tensor of size 2x4 to m
m + torch.rand(2, 4)

tensor([[2.8250, 5.6536, 3.1991, 7.4905],
        [4.3494, 2.6762, 1.0401, 9.2063]])

In [23]:
# Subtract a random tensor of size 2x4 to m
m - torch.rand(2, 4)

tensor([[1.5435, 4.6138, 2.6342, 6.2149],
        [3.3711, 1.7445, 0.5835, 8.0788]])

In [24]:
# Multiply a random tensor of size 2x4 to m
m * torch.rand(2, 4)

tensor([[1.6658, 4.8620, 1.5543, 1.4039],
        [3.3072, 0.7778, 0.5308, 8.7711]])

In [25]:
# Divide m by a random tensor of size 2x4
m / torch.rand(2, 4)

tensor([[  9.1125,  18.0217,   6.8425, 155.3573],
        [  4.3220, 691.7441,   1.9628,  34.9093]])

In [26]:
m.size()

torch.Size([2, 4])

In [27]:
# Transpose tensor m, which is essentially 2x4 to 4x2
m.t()

tensor([[2., 4.],
        [5., 2.],
        [3., 1.],
        [7., 9.]])

In [28]:
# Same as
m.transpose(0, 1)

tensor([[2., 4.],
        [5., 2.],
        [3., 1.],
        [7., 9.]])

## Constructors

In [ ]:
# Create tensor from 3 to 8, with each having a space of 1
torch.arange(3., 8 + 1)

In [ ]:
# Create tensor from 5.7 to -2.1 with each having a space of -3
torch.arange(5.7, -2.1, -3)

In [ ]:
# returns a 1D tensor of steps equally spaced points between start=3, end=8 and steps=20
torch.linspace(3, 8, 20).view(1, -1)

In [ ]:
# Create a tensor filled with 0's
torch.zeros(3, 5)

In [ ]:
# Create a tensor filled with 1's
torch.ones(3, 2, 5)

In [ ]:
# Create a tensor with the diagonal filled with 1
torch.eye(3)

In [ ]:
# Set default plots
from res.plot_lib import set_default
from matplotlib import pyplot as plt
set_default()

In [ ]:
# Numpy bridge!
plt.hist(torch.randn(1000).numpy(), 100);

In [ ]:
plt.hist(torch.randn(10**6).numpy(), 100);  # how much does this chart weight?
# use rasterized=True for SVG/EPS/PDF!

In [ ]:
plt.hist(torch.rand(10**6).numpy(), 100);

## Casting

In [ ]:
# Helper to get what kind of tensor types
torch.*Tensor?

In [ ]:
m

In [ ]:
# This is basically a 64 bit float tensor
m_double = m.double()
m_double

In [ ]:
# This creates a tensor of type int8
m_byte = m.byte()
m_byte

In [ ]:
# Move your tensor to GPU device 0 if there is one (first GPU in the system)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
m.to(device)

In [ ]:
# Converts tensor to numpy array
m_np = m.numpy()
m_np

In [ ]:
# In-place fill of column 0 and row 0 with value -1
m_np[0, 0] = -1
m_np

In [ ]:
m

In [ ]:
# Create a tensor of integers ranging from 0 to 4
import numpy as np
n_np = np.arange(5)
n = torch.from_numpy(n_np)
print(n_np, n)

In [ ]:
# In-place multiplication of all elements by 2 for tensor n
# Because n is essentiall n_np, not a clone, this affects n_np
n.mul_(2)
n_np

## More fun

In [29]:
# Creates two tensor of size 1x4
a = torch.Tensor([[1, 2, 3, 4]])
b = torch.Tensor([[5, 6, 7, 8]])
print(a.size(), b)

torch.Size([1, 4]) tensor([[5., 6., 7., 8.]])


In [ ]:
# Concatenate on axis 0, so you get 2x4
torch.cat((a, b), 0)

In [ ]:
# Concatenate on axis 1, so you get 1x8
torch.cat((a, b), 1)

## Much more

There's definitely much more, but this was the basics about `Tensor`s fun.

*Torch* full API should be read at least once.
Hence, go [here](https://pytorch.org/docs/stable/index.html).
You'll find 100+ `Tensor` operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described.